services:
  backend:
    build: ./apps/backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - mongo
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build: ./apps/frontend
    container_name: frontend
    ports:
      - "5173:80"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_db
    command: mongod --quiet
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
